name: 'mongodb with single node cluster'
description: 'Start mongodb with single node cluster'
author: 'gucao'
branding:
  icon: 'database'
  color: 'yellow'
inputs:
  VERSION:
    description: 'image tag version'
    required: false
    default: latest
  USERNAME:
    description: 'MONGO_INITDB_ROOT_USERNAME - root username'
    required: false
    default: 'mongo'
  PASSWORD:
    description: 'MONGO_INITDB_ROOT_PASSWORD - root user password'
    required: false
    default: '123123'
runs:
  using: 'docker'
  image: 'Dockerfile'
